[package]
name = "zmapr"
version = "0.0.2-WIP"
description = "Code and content mapper for AI-optimized context."
edition = "2024"
license = "MIT OR Apache-2.0"
keywords = ["coding-harness","coding-ai"]
authors = ["Jeremy Chone"]
homepage = "https://github.com/zcoder-run/rust-zmapr"
repository = "https://github.com/zcoder-run/rust-zmapr"


[lib]
doctest = false

[lints.rust]
unsafe_code = "forbid"
# unused = { level = "allow", priority = -1 } # For exploratory dev.

[dependencies]
# -- Async
tokio = { version = "1", features = ["full"] }
# -- AI
genai = "0.7.0-beta.15"
# -- Serde
serde = { version = "1", features = ["derive"] }
serde_with = { version = "3", features = ["macros"] }
# -- Content Formats
htmlr = "0.1"
# -- FS & Http
reqwest = "0.13"
simple-fs = "0.12"

# -- Others
derive_more = { version = "2", features = ["from", "display"] }
macro_rules_attribute = "0.2"
