#![doc = include_str!("../../docs/rustdoc/mapr/mapr-ai.md")]

use genai::Client as GenaiClient;
use genai::chat::{ChatMessage, ChatRequest};
use std::fmt::Debug;
use std::future::Future;
use std::pin::Pin;
use std::sync::{Arc, RwLock};

/// Sendable boxed future returned by AI completion clients.
pub type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

// region:    --- Types

/// Result of an AI completion call containing the generated text and optional token usage.
#[derive(Debug, Clone, Default)]
pub struct MaprAiResponse {
	/// Text generated by the AI client.
	pub content: String,

	/// Token usage reported or estimated by the client, when available.
	pub usage: Option<genai::chat::Usage>,
}

/// Trait abstracting AI completion calls for content mapping.
pub trait MaprAiClient: Debug + Send + Sync {
	/// Generate a completion for `prompt`.
	fn complete<'a>(&'a self, prompt: &'a str) -> BoxFuture<'a, crate::Result<MaprAiResponse>>;
}

/// Selector determining which AI client implementation to instantiate.
#[derive(Debug, Clone, Default)]
pub enum MaprAiSelector {
	#[default]
	/// Use the genai-backed provider client.
	Real,

	/// Use the deterministic local client.
	Stub,

	/// Use the supplied client implementation.
	Custom(Arc<dyn MaprAiClient>),
}

/// Deterministic stub AI client for offline testing.
#[derive(Debug, Clone, Default)]
pub struct StubAiClient {
	custom_response: Option<String>,
	custom_usage: Option<genai::chat::Usage>,
}

/// Real genai-backed AI client placeholder.
#[derive(Debug, Clone)]
pub struct GenaiAiClient {
	model: String,
	client: Option<GenaiClient>,
}

// endregion: --- Types

// region:    --- Implementations

impl MaprAiSelector {
	/// Create a client from this selector, using `model` for the real client.
	pub fn create_client(&self, model: &str) -> Arc<dyn MaprAiClient> {
		match self {
			Self::Real => Arc::new(GenaiAiClient::new(model)),
			Self::Stub => Arc::new(StubAiClient::default()),
			Self::Custom(client) => client.clone(),
		}
	}
}

impl MaprAiResponse {
	/// Create a response with no token usage information.
	pub fn new(content: impl Into<String>) -> Self {
		Self {
			content: content.into(),
			usage: None,
		}
	}

	/// Attach token usage information to this response.
	/// Configure the token usage returned by this stub.
	pub fn with_usage(mut self, usage: genai::chat::Usage) -> Self {
		self.usage = Some(usage);
		self
	}
}

impl StubAiClient {
	/// Create a stub that always returns `response`.
	pub fn from_response(response: impl Into<String>) -> Self {
		Self {
			custom_response: Some(response.into()),
			custom_usage: None,
		}
	}

	/// Configure the response returned by this stub.
	pub fn with_response(mut self, response: impl Into<String>) -> Self {
		self.custom_response = Some(response.into());
		self
	}

	pub fn with_usage(mut self, usage: genai::chat::Usage) -> Self {
		self.custom_usage = Some(usage);
		self
	}
}

impl GenaiAiClient {
	/// Create a provider-backed client for `model`.
	pub fn new(model: impl Into<String>) -> Self {
		Self {
			model: model.into(),
			client: GenaiClient::new().ok(),
		}
	}

	/// Use an already configured genai client.
	pub fn with_client(mut self, client: GenaiClient) -> Self {
		self.client = Some(client);
		self
	}

	/// Return the model name used for completion requests.
	pub fn model(&self) -> &str {
		&self.model
	}
}

// endregion: --- Implementations

// region:    --- Trait Implementations

impl<T: ?Sized + MaprAiClient> MaprAiClient for Arc<T> {
	fn complete<'a>(&'a self, prompt: &'a str) -> BoxFuture<'a, crate::Result<MaprAiResponse>> {
		(**self).complete(prompt)
	}
}

impl MaprAiClient for StubAiClient {
	fn complete<'a>(&'a self, prompt: &'a str) -> BoxFuture<'a, crate::Result<MaprAiResponse>> {
		let response = if let Some(custom) = &self.custom_response {
			custom.clone()
		} else if let Some(content) = sanitize_input_from_prompt(prompt) {
			format!("<SANITIZED_CONTENT>{content}</SANITIZED_CONTENT>")
		} else {
			let hash = blake3::hash(prompt.as_bytes()).to_hex();
			let short_hash = &hash[..8];
			format!(
				"<FILE_INFO>\n{{\n  \"summary\": \"Stub summary for content ({short_hash})\",\n  \"when_to_use\": \"Consult when evaluating stub mapping.\",\n  \"public_types\": [],\n  \"public_functions\": [],\n  \"topics\": [\"stub\", \"test\"]\n}}\n</FILE_INFO>"
			)
		};
		let usage = self.custom_usage.clone().unwrap_or_else(|| {
			let prompt_tokens = (prompt.len() / 4).max(1) as i32;
			let completion_tokens = (response.len() / 4).max(1) as i32;
			let total_tokens = prompt_tokens + completion_tokens;
			genai::chat::Usage {
				prompt_tokens: Some(prompt_tokens),
				completion_tokens: Some(completion_tokens),
				total_tokens: Some(total_tokens),
				..Default::default()
			}
		});

		Box::pin(async move { Ok(MaprAiResponse::new(response).with_usage(usage)) })
	}
}

impl MaprAiClient for GenaiAiClient {
	fn complete<'a>(&'a self, prompt: &'a str) -> BoxFuture<'a, crate::Result<MaprAiResponse>> {
		let model_name = self.model.clone();
		let client = self.client.clone();
		let prompt_owned = prompt.to_string();

		Box::pin(async move {
			let client = match client {
				Some(c) => c,
				None => GenaiClient::new()
					.map_err(|err| crate::Error::custom(format!("genai client initialization error: {err}")))?,
			};

			let chat_req = ChatRequest::new(vec![ChatMessage::user(prompt_owned)]);
			let chat_res = client
				.exec_chat(&model_name, chat_req, None)
				.await
				.map_err(|err| crate::Error::custom(format!("genai completion error: {err}")))?;

			let text = chat_res
				.first_text()
				.ok_or_else(|| crate::Error::custom("genai response did not contain text content"))?
				.to_string();

			Ok(MaprAiResponse::new(text).with_usage(chat_res.usage))
		})
	}
}

// endregion: --- Trait Implementations

// region:    --- Support

fn sanitize_input_from_prompt(prompt: &str) -> Option<&str> {
	let start_tag = "<SANITIZE_INPUT>";
	let end_tag = "</SANITIZE_INPUT>";
	let content_start = prompt.find(start_tag)? + start_tag.len();
	let remaining = prompt.get(content_start..)?;
	let content_end = remaining.find(end_tag)?;
	prompt.get(content_start..content_start + content_end)
}

static ACTIVE_SELECTOR: RwLock<Option<MaprAiSelector>> = RwLock::new(None);

/// Set or clear the process-wide selector used by default client selection.
pub fn set_active_ai_selector(selector: Option<MaprAiSelector>) {
	if let Ok(mut guard) = ACTIVE_SELECTOR.write() {
		*guard = selector;
	}
}

/// Return the process-wide selector, or the default real-client selector.
pub fn get_active_ai_selector() -> MaprAiSelector {
	ACTIVE_SELECTOR.read().ok().and_then(|guard| guard.clone()).unwrap_or_default()
}

/// Select a client using `selector`, or the active process-wide selector when absent.
pub fn select_ai_client(selector: Option<&MaprAiSelector>, model: &str) -> Arc<dyn MaprAiClient> {
	if let Some(explicit) = selector {
		explicit.create_client(model)
	} else {
		let active = get_active_ai_selector();
		active.create_client(model)
	}
}

/// Select a client using the active process-wide selector.
pub fn select_active_ai_client(model: &str) -> Arc<dyn MaprAiClient> {
	select_ai_client(None, model)
}

// endregion: --- Support

// region:    --- Tests

#[cfg(test)]
mod tests {
	use super::*;

	#[tokio::test]
	async fn test_stub_ai_client_default() -> crate::Result<()> {
		let client = StubAiClient::default();
		let response = client.complete("Sample file content to summarize").await?;

		assert!(response.content.contains("<FILE_INFO>"));
		assert!(response.content.contains("</FILE_INFO>"));
		assert!(response.content.contains("\"summary\":"));
		assert!(response.content.contains("\"when_to_use\":"));
		assert!(response.content.contains("\"topics\":"));
		assert!(response.usage.is_some());

		Ok(())
	}

	#[tokio::test]
	async fn test_stub_ai_client_custom_response() -> crate::Result<()> {
		let custom = "<FILE_INFO>\n{\"summary\": \"Custom summary\"}\n</FILE_INFO>";
		let client = StubAiClient::from_response(custom);
		let response = client.complete("irrelevant input").await?;

		assert_eq!(response.content, custom);

		Ok(())
	}

	#[tokio::test]
	async fn test_genai_client_creation_and_error() -> crate::Result<()> {
		let client = GenaiAiClient::new("mock-model");
		assert_eq!(client.model(), "mock-model");

		let result = client.complete("irrelevant input").await;
		assert!(result.is_err());

		Ok(())
	}

	#[tokio::test]
	async fn test_selector_and_active_override() -> crate::Result<()> {
		let client = select_ai_client(Some(&MaprAiSelector::Stub), "gpt-5");
		let response = client.complete("test prompt").await?;
		assert!(response.content.contains("<FILE_INFO>"));

		set_active_ai_selector(Some(MaprAiSelector::Stub));
		let active_client = select_active_ai_client("gpt-5");
		let active_resp = active_client.complete("test prompt").await?;
		assert!(active_resp.content.contains("<FILE_INFO>"));

		// Reset active selector
		set_active_ai_selector(None);

		Ok(())
	}
}

// endregion: --- Tests
